export {default as LoginPage} from './Login/Login'
export {default as ProfilePage} from './Profile/Profile'
export {default as RegistrationPage} from './Registration/Registration'
export {default as RestorePasswordPage} from './RestorePassword/RestorePassword'
export {default as NewPasswordPage} from './NewPassword/NewPassword'
export {default as NotFound} from './NotFound/NotFound'
