export const HOME = '/'
export const PROFILE = '/profile'
export const LOGIN = '/login'
export const REGISTRATION = '/registration'
export const RESTORE_PASSWORD = '/restore-password'
export const NEW_PASSWORD = '/set-new-password/:token?'
